import { Media } from '../../modules/labeler/interfaces';

export const mediasMock: Media[] = [
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'XBeruI-sY3l6QUH9tzF1h',
    link: 'https://drive.google.com/uc?export=view&id=1SqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG2023014.png',
    observation: '',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYop',
    link: 'https://drive.google.com/uc?id=16huCpPPQ9-assmmn-4OWkXxG7sD6NXcO&export=view',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo1',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo2',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo3',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo4',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo5',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo6',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo7',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo8',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo9',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo11',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
  {
    author: {
      id: 'dzQ5y1R3h7xZJZi5CheO3',
      firstName: 'Zoey',
      lastName: 'de Souza Pessanha',
    },
    filedate: '2023-07-28',
    id: 'KdDqmgavkyPiNnPZy3pYo12',
    link: 'https://drive.google.com/uc?export=view&id=1YqVklE01-XPX-6iAO0iYie5acOCk0rhk',
    filename: 'IMG20230126.png',
    observation: 'anotado',
    sensible: false,
    tags: [
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'fulano_da_silva',
        id: 'k5xVu-N9xFCfQ1zVuN_bB',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'redes',
        id: 'xbw18KtUS-mXBwSnNGdgz',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'peixes',
        id: 'GuI3YX32s2b524XdRHtAp',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'mar',
        id: 'EXvXAzSJnncorBnjidWs1',
      },
      {
        categoryId: 'T5Bi90TJhj17tnkBKfIvD',
        label: 'barco',
        id: 'zqm1Fmi8GZaXiF-XbNGna',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'beltrano',
        id: 'O_G9N7qEfIsWFC4Ve09Q5',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'ciclano',
        id: 'QCnSIdACZuETsqoTCCZk1',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'json',
        id: '0NUKzchANMd8LSXupEy17',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'python',
        id: 'jDNIvWg_5c9wGJOojlfsq',
      },
      {
        categoryId: '5jENKicDl4PKNXIYpddUt',
        label: 'jhon',
        id: '09PjlKda4ikDD9_oJIR_5',
      },
    ],
    altText: 'image',
    type: 'IMAGEM',
  },
];
